name: NS 固件自动镜像同步

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  Firmware:
    runs-on: ubuntu-latest
    steps:
    
      - name: 安装 Python
        uses: actions/setup-python@v2.3.1
      - name: 安装阿里云盘 cli
        run: pip install aliyunpan
        
      - name: 下载最新的 5 个固件
        run: |
             cd $HOME
             VERSION1=$(curl -fsL "https://archive.org/download/nintendo-switch-global-firmwares/Official%20Global%20Firmware%20MD5%20Hashs.txt" | sed 's/\t/\n/g' | grep "Firmware" | head -2 | tail -1)
             VERSION2=$(curl -fsL "https://archive.org/download/nintendo-switch-global-firmwares/Official%20Global%20Firmware%20MD5%20Hashs.txt" | sed 's/\t/\n/g' | grep "Firmware" | head -3 | tail -1)
             VERSION3=$(curl -fsL "https://archive.org/download/nintendo-switch-global-firmwares/Official%20Global%20Firmware%20MD5%20Hashs.txt" | sed 's/\t/\n/g' | grep "Firmware" | head -4 | tail -1)
             VERSION4=$(curl -fsL "https://archive.org/download/nintendo-switch-global-firmwares/Official%20Global%20Firmware%20MD5%20Hashs.txt" | sed 's/\t/\n/g' | grep "Firmware" | head -5 | tail -1)
             VERSION5=$(curl -fsL "https://archive.org/download/nintendo-switch-global-firmwares/Official%20Global%20Firmware%20MD5%20Hashs.txt" | sed 's/\t/\n/g' | grep "Firmware" | head -6 | tail -1)
             echo "下载 ${VERSION1}"
             echo "VERSION1=${VERSION1}" >> $GITHUB_ENV
             aria2c -s8 -j8 -x8 "https://archive.org/download/nintendo-switch-global-firmwares/${VERSION1}.zip" -o "${VERSION1/ /_}.zip"
             echo "下载 ${VERSION2}"
             echo "VERSION2=${VERSION2}" >> $GITHUB_ENV
             aria2c -s8 -j8 -x8 "https://archive.org/download/nintendo-switch-global-firmwares/${VERSION2}.zip" -o "${VERSION2/ /_}.zip"
             echo "下载 ${VERSION3}"
             echo "VERSION3=${VERSION3}" >> $GITHUB_ENV
             aria2c -s8 -j8 -x8 "https://archive.org/download/nintendo-switch-global-firmwares/${VERSION2}.zip" -o "${VERSION3/ /_}.zip"
             echo "下载 ${VERSION4}"
             echo "VERSION4=${VERSION4}" >> $GITHUB_ENV
             aria2c -s8 -j8 -x8 "https://archive.org/download/nintendo-switch-global-firmwares/${VERSION2}.zip" -o "${VERSION4/ /_}.zip"
             echo "下载 ${VERSION5}"
             echo "VERSION5=${VERSION5}" >> $GITHUB_ENV
             aria2c -s8 -j8 -x8 "https://archive.org/download/nintendo-switch-global-firmwares/${VERSION2}.zip" -o "${VERSION5/ /_}.zip"
             
      - name: 清空上次同步的固件
        continue-on-error: true
        env:
          refreshtoken: ${{ secrets.REFRESH_TOKEN }}
        run: |
          echo "尝试清空固件文件夹"
          FWTODELETE_ALI_ARR=($(aliyunpan-cli -t ${refreshtoken} ls NSEmuHelper/NSFirmwareMirror | sed "s/\t/ /g")); echo ${FWTODELETE_ALI_ARR[@]}
          for fw_name in ${FWTODELETE_ALI_ARR[@]}
          do
            aliyunpan-cli -t ${refreshtoken} rm "NSEmuHelper/NSFirmwareMirror/${fw_name}"
          done
         
      - name: 上传固件到阿里云盘
        env:
          refreshtoken: ${{secrets.REFRESH_TOKEN}}
        run: |
          VERSION1="${{ env.VERSION1 }}"
          VERSION2="${{ env.VERSION2 }}"
          VERSION3="${{ env.VERSION3 }}"
          VERSION4="${{ env.VERSION4 }}"
          VERSION5="${{ env.VERSION5 }}"
          aliyunpan-cli -t ${refreshtoken} upload -f "$HOME/${VERSION1/ /_}.zip" NSEmuHelper/NSFirmwareMirror
          aliyunpan-cli -t ${refreshtoken} upload -f "$HOME/${VERSION2/ /_}.zip" NSEmuHelper/NSFirmwareMirror
          aliyunpan-cli -t ${refreshtoken} upload -f "$HOME/${VERSION3/ /_}.zip" NSEmuHelper/NSFirmwareMirror
          aliyunpan-cli -t ${refreshtoken} upload -f "$HOME/${VERSION4/ /_}.zip" NSEmuHelper/NSFirmwareMirror
          aliyunpan-cli -t ${refreshtoken} upload -f "$HOME/${VERSION5/ /_}.zip" NSEmuHelper/NSFirmwareMirror

