name: NS 模拟器自动镜像同步

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/4 * * *'

jobs:
  YuzuEA:
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新构建版本号和 URL
        run: |
             VERSION=$(curl -H "Authorization: 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" "https://api.github.com/repos/pineappleea/pineapple-src/releases" | grep "tag_name\": \"EA" | head -1)
             VERSION=${VERSION// /};VERSION=${VERSION//\"/};VERSION=${VERSION//tag_name:EA-/};VERSION=${VERSION//,/}
             echo "版本号为：${VERSION}"
             URL="https://github.com/pineappleEA/pineapple-src/releases/download/EA-${VERSION}/Windows-Yuzu-EA-${VERSION}.7z"
             echo "链接为：${URL}"
             echo "VERSION=${VERSION}" >> $GITHUB_ENV
             echo "URL=${URL}" >> $GITHUB_ENV
      - name: 安装 rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: 检查构建是否重复
        run: |
          CHECK_REPEATED="No"
          echo "CHECK_REPEATED=${CHECK_REPEATED}" >> $GITHUB_ENV
          VERSION="${{ env.VERSION }}"
          rclone lsjson e5:/NSEmuHelper/YuzuEarlyAccess | jq -rc '.[]' | while read item;do
            TMP_VERSION="`printf "$item" | jq -rc '.Name' | awk -F'.' '{print $1}' | awk -F'-' '{print $4}'`"
            if [ "${TMP_VERSION}" = "${VERSION}" ]; then
             CHECK_REPEATED="Yes"
             echo "YES YES YES"
             echo "CHECK_REPEATED=${CHECK_REPEATED}" >> $GITHUB_ENV
            fi
          done
      - name: 下载最新构建
        if: ${{ env.CHECK_REPEATED == 'No' }}
        run: |
             cd /tmp
             echo "下载 ${{ env.URL }}"
             curl --retry 5 --retry-delay 2 -fL "${{ env.URL }}" -o "/tmp/Windows-Yuzu-EA-${{ env.VERSION }}.7z"
      - name: 上传构建到 OneDrive
        if: ${{ env.CHECK_REPEATED == 'No' }}
        run: |
            rclone copy "/tmp/Windows-Yuzu-EA-${{ env.VERSION }}.7z" e5:/NSEmuHelper/YuzuEarlyAccess
  YuzuMainline:
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新构建版本号和 URL
        run: |
             VERSION=$(curl -H "Authorization: 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" "https://api.github.com/repos/yuzu-emu/yuzu-mainline/releases/latest" | jq -r .tag_name)
             VERSION=${VERSION//mainline-0-/};
             echo "版本号为：${VERSION}"
             URL=$(curl https://api.github.com/repos/yuzu-emu/yuzu-mainline/releases/latest | grep "browser_download_url" | grep "yuzu-windows-msvc" | grep "7z")
             URL=${URL// /};URL=${URL//\"/};URL=${URL//browser_download_url:/};URL=${URL//,/}
             echo "链接为：${URL}"
             echo "VERSION=${VERSION}" >> $GITHUB_ENV
             echo "URL=${URL}" >> $GITHUB_ENV
      - name: 安装 rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: 检查构建是否重复
        run: |
          CHECK_REPEATED="No"
          echo "CHECK_REPEATED=${CHECK_REPEATED}" >> $GITHUB_ENV
          VERSION="${{ env.VERSION }}"
          rclone lsjson e5:/NSEmuHelper/YuzuMainline | jq -rc '.[]' | while read item;do
            TMP_VERSION="`printf "$item" | jq -rc '.Name' | awk -F'.' '{print $1}' | awk -F'-' '{print $4}'`"
            if [ "${TMP_VERSION}" = "${VERSION}" ]; then
             CHECK_REPEATED="Yes"
             echo "YES YES YES"
             echo "CHECK_REPEATED=${CHECK_REPEATED}" >> $GITHUB_ENV
            fi
          done
      - name: 下载最新构建
        if: ${{ env.CHECK_REPEATED == 'No' }}
        run: |
             cd /tmp
             echo "下载 ${{ env.URL }}"
             curl --retry 5 --retry-delay 2 -fL "${{ env.URL }}" -o "/tmp/yuzu-windows-msvc-${{ env.VERSION }}.7z"
      - name: 上传构建到 OneDrive
        if: ${{ env.CHECK_REPEATED == 'No' }}
        run: |
            rclone copy "/tmp/yuzu-windows-msvc-${{ env.VERSION }}.7z" e5:/NSEmuHelper/YuzuMainline

  RyujinxMainline:
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新构建版本号和 URL
        run: |
             VERSION=$(curl -H "Authorization: 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" "https://api.github.com/repos/Ryujinx/release-channel-master/releases/latest" | jq -r .tag_name)
             echo "版本号为：${VERSION}"
             URL="https://github.com/Ryujinx/release-channel-master/releases/download/${VERSION}/ryujinx-${VERSION}-win_x64.zip"
             echo "链接为：${URL}"
             echo "VERSION=${VERSION}" >> $GITHUB_ENV
             echo "URL=${URL}" >> $GITHUB_ENV
      - name: 安装 rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: 检查构建是否重复
        run: |
          CHECK_REPEATED="No"
          echo "CHECK_REPEATED=${CHECK_REPEATED}" >> $GITHUB_ENV
          VERSION="${{ env.VERSION }}"
          rclone lsjson e5:/NSEmuHelper/Ryujinx | jq -rc '.[]' | while read item;do
            TMP_VERSION="`printf "$item" | jq -rc '.Name' | awk -F'.' '{print $1}' | awk -F'-' '{print $2}'`"
            if [ "${TMP_VERSION}" = "${VERSION}" ]; then
             CHECK_REPEATED="Yes"
             echo "YES YES YES"
             echo "CHECK_REPEATED=${CHECK_REPEATED}" >> $GITHUB_ENV
            fi
          done
      - name: 下载最新构建
        if: ${{ env.CHECK_REPEATED == 'No' }}
        run: |
             cd /tmp
             echo "下载 ${{ env.URL }}"
             curl --retry 5 --retry-delay 2 -fL "${{ env.URL }}" -o "/tmp/ryujinx-${{ env.VERSION }}-win_x64.zip"
      - name: 上传构建到 OneDrive
        if: ${{ env.CHECK_REPEATED == 'No' }}
        run: |
            rclone copy "/tmp/ryujinx-${{ env.VERSION }}-win_x64.zip" e5:/NSEmuHelper/Ryujinx
