name: Yuzu 预先测试版自动同步

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 12 * * ?'

jobs:
  自动同步:
    runs-on: ubuntu-latest
    steps:
      - name: 下载最新构建
        uses: XAMPPRocky/get-github-release@v1
        with:
          matches: Windows-Yuzu-EA
          owner: pineappleEA
          repo: pineapple-src
          token: "${{ secrets.GITHUB_TOKEN }}"