name: Yuzu 预先测试版自动同步

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  AutoSynchronization:
    runs-on: ubuntu-latest
    steps:
      - name: 获取最新构建版本号和 URL 并且下载
        run: |
             VERSION=$(curl https://api.github.com/repos/pineappleea/pineapple-src/releases | grep "tag_name\": \"EA" | head -1)
             VERSION=${VERSION// /};VERSION=${VERSION//\"/};VERSION=${VERSION//tag_name:EA-/};VERSION=${VERSION//,/}
             echo "版本号为：${VERSION}"
             URL="https://github.com/pineappleEA/pineapple-src/releases/download/EA-${VERSION}/Windows-Yuzu-EA-${VERSION}.7z"
             echo "链接为：${URL}"
             cd /tmp
             curl -fL "${URL}" -O "/tmp/Windows-Yuzu-EA-${VERSION}.7z"
             ls /tmp
      - name: 上传构建到 WebDAV
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.WEBDAV_ADDRESS}}
          webdav_username: ${{secrets.WEBDAV_USERNAME}}
          webdav_password: ${{secrets.WEBDAV_PASSWORD}}
          webdav_upload_path: "/123pan/YuzuEAMirror"
          files: "/tmp/Windows-Yuzu-EA-*.7z"
